name: CI-CD

on:
  workflow_dispatch:
    inputs:
      isRelease:
        type: boolean
        description: is Release to TestFlight
jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: echo "isRelease is ${{ github.event.inputs.isRelease }}"
