name: CI-CD
run-name: Run Unit Test / UI Test on ${{ inputs.branch }} branch

on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=16.2,name=iPhone 14 Pro Max']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run SwiftLint
        run: echo SwiftLint running...
      - name: Carthage Update
        continue-on-error: true
        run: carthage update --platform iOS --no-use-binaries --use-xcframeworks
      - name: Run Script Build Carthage
        run: bash carthage-build.sh build --platform iOS --use-xcframeworks
      - name: Build
        run: xcodebuild clean build -project TestCICD.xcodeproj -scheme TestCICD -destination "${destination}" CODE_SIGN_IDENTITY="" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
        env:
          destination: ${{ matrix.destination }}
      - name: Test
        run: xcodebuild clean test -project TestCICD.xcodeproj -scheme "TestCICDTests" -destination "${destination}" CODE_SIGN_IDENTITY="" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
        env:
          destination: ${{ matrix.destination }}

