name: CI-Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=16.2,name=iPhone 14 Pro Max']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run SwiftLint
        run: echo SwiftLint running...
      - name: CARTHAGE UPDATE
        run: carthage update --platform iOS --no-use-binaries --use-xcframeworks
      - name: RUN SCRIPT BUILD CARTHAGE
        if: always()
        run: bash carthage-build.sh build --platform iOS --use-xcframeworks
      - name: Build
        run: xcodebuild clean build -project TestCICD.xcodeproj -scheme TestCICD -destination "${destination}" CODE_SIGN_IDENTITY="" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
        env:
          destination: ${{ matrix.destination }}
      - name: Test
        run: xcodebuild clean test -project TestCICD.xcodeproj -scheme "TestCICDTests" -destination "${destination}" CODE_SIGN_IDENTITY="" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
        env:
          destination: ${{ matrix.destination }}
