name: CI-Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=16.2,name=iPhone 14 Pro Max']
    steps:
      # - name: Select Xcode
      #   run: sudo xcode-select -switch /Applications/Xcode_14.2.app
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: xcodebuild clean build -project TestCICD.xcodeproj -scheme TestCICD -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=16.2,name=iPhone 14 Pro Max' ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
      - name: Test
        run: xcodebuild clean test -project TestCICD.xcodeproj -scheme TestCICDTests -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=16.2,name=iPhone 14 Pro Max' ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
