name: CI

on:
  workflow_dispatch:
    inputs:
      boolean:
        type: boolean
        description: is Release to TestFlight
jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: |
          echo "boolean is ${{ github.event.inputs.boolean }}"
